settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: rabbit-can-middleware
  path: .
  commands: 
    run:
      status: true
  watcher:
    extensions:
    - go
    - lock
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    - vendor.orig
