version: '2'

services:
  redis:
    restart: always
    image: redis
    volumes:
      - /my/own/datadir:/data
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
  server:
    build: .
    command: realize start --server
    volumes:
      - .:/go/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/bin/docker
    ports:
      - 1234:1234
      - 5002:5002
    links:
      - redis
