version: '2'

services:
  server:
    build: .
    command: realize start --server
    volumes:
      - .:/go/src/app
      - dep_ensure:/go/src/app/vendor
    ports:
      - 1234:1234
      - 5002:5002

volumes:
  dep_ensure:
    driver: local
